### ISSUE TITLE
DeviceGroup sync method does not exist. 

### ISSUE THREAD

**Issue by amccrea** [F5Networks/f5-common-python#1041]
Class DeviceGroup has a method sync(), which calls f5.bigip.cm.Cm's sync method (:meth:`~f5.bigip.cm.Cm.sync`), which does not exist. 

http://f5-sdk.readthedocs.io/en/latest/_modules/f5/bigip/tm/cm/device_group.html#Device_Group.sync

```
> y
<f5.bigip.tm.cm.device_group.Device_Group object at 0x1098a69e8>
> y.sync
<bound method Device_Group.sync of <f5.bigip.tm.cm.device_group.Device_Group object at 0x1098a69e8>>
> y.sync()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/f5/bigip/tm/cm/device_group.py", line 63, in sync
    cm.sync(self.name)
  File "/usr/local/lib/python3.6/site-packages/f5/bigip/mixins.py", line 102, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.cm.Cm'>' object has no attribute 'sync'
```

**Comment by wojtek0806** [comment]
@amccrea 

This issue has been caused by removal of custom sync method from CM endpoint, this is because running sync, will work when 'run' command is used. I will rework this sync() method. 

Please be aware tho that we generally avoid setting up methods like this, as this SDK supposed to remain as bare-bones as possible.

Submitting PR soon

**Comment by amccrea** [comment]
@wojtek0806 Noted. And thanks a lot!
