### ISSUE TITLE
Insecure warning messages

### ISSUE THREAD

**Issue by himalayanBuddy** [F5Networks/f5-common-python#1093]
I am getting the below Insecure warning messages. 

C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:853: I
nsecureRequestWarning: Unverified HTTPS request is being made. Adding certificat
e verification is strongly advised. See: https://urllib3.readthedocs.io/en/lates
t/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

When I disable the warning message in the file connectionpool.py. I stop getting those message.

```
        if not conn.is_verified:
            warnings.warn((
                'Unverified HTTPS request is being made. '
                'Adding certificate verification is strongly advised. See: '
                'https://urllib3.readthedocs.io/en/latest/advanced-usage.html'
                '#ssl-warnings'),
                InsecureRequestWarning)
```

I just commented out the warning message to not receive those.

    ```
    if not conn.is_verified:
          pass
            #warnings.warn((
            #    'Unverified HTTPS request is being made. '
             #   'Adding certificate verification is strongly advised. See: '
             #   'https://urllib3.readthedocs.io/en/latest/advanced-usage.html'
              #  '#ssl-warnings'),
              #  InsecureRequestWarning)

```

Generally BIGIP uses self-signed certificates. Is it requirement for f5-sdk app to throw Insecure certificate warning.

**Comment by vsnine** [comment]
It's a requirement of the urllib3 library that the f5-sdk uses, if I recall correctly. A quick read about urllib3 suggests that you may be able to provide the BIG-IP's certificate as a CA cert, but I'm not sure yet if this functionality is exposed by the f5-sdk.

A quick way to disable the warning should be:
```
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

I'd personally like to have the option (or documentation if it already exists) to provide a CA cert somehow.

**Comment by caphrim007** [comment]
I do not think this is an exposed option at this time. However, this issue could serve as a feature request for it.

**Comment by vsnine** [comment]
I did some testing on this and it appears that setting the following, with the file ca.crt containing a copy of the SSL cert used on the BIG-IP in question, this seems to work. As a test, I pointed the script to the the HA peer of the cluster, and the script had a hard failure. Obviously, using self-signed certs doesn't scale well, but at least you would know that you are talking to the correct unit.

The second part suppresses warnings thrown due to my using python 2.7. They are likely not needed in all cases but I figured I would throw them into my example anyway. 

```
# force validation of the cert against a CA or self-signed cert
import os
os.environ['REQUESTS_CA_BUNDLE'] = 'ca.crt'

# suppress warning messages due to using python 2.7
import requests
from requests.packages.urllib3.exceptions import SNIMissingWarning, InsecurePlatformWarning, SubjectAltNameWarning
requests.packages.urllib3.disable_warnings(SNIMissingWarning)
requests.packages.urllib3.disable_warnings(InsecurePlatformWarning)
requests.packages.urllib3.disable_warnings(SubjectAltNameWarning)

```

**Comment by magnuswatn** [comment]
The override with the REQUESTS_CA_BUNDLE environment variable only works because of a bug in requests ([#3829](https://github.com/requests/requests/issues/3829)) and it only works with a session. So be aware that if you use token auth against the F5, the first request (with the username and password) will be without certificate validation, even with the REQUESTS_CA_BUNDLE environment variable.
