### ISSUE TITLE
Add support for partitionAccess for Auth User

### ISSUE THREAD

**Issue by gabrielfortin** [F5Networks/f5-common-python#1144]
Auth User includes an option for partitionAccess but it is not currently supported. I would like to be able to add, modify and delete the partitionAccess of a Auth User.

**Comment by caphrim007** [comment]
@GabrielFortin how do you mean?

the following works without issue depending on the version of BIG-IP in use.

```
mgmt.tm.auth.users.user.create(
    name="foo", partitionAccess=[{ name="all-partitions", role="admin" }]
)
```

**Comment by gabrielfortin** [comment]
@caphrim007  I meant that partitionAccess is not a seperate class like pool members is, for example. I was wondering, partitionAccess and pool members being two lists respectively in auth user and ltm pool, why pool members is a subclass and partitionAccess isn't? Thank you

**Comment by caphrim007** [comment]
the reason is because pool members is itself a collection of resources. it lives at a different url than the partitionAccess does, ie

pool/name/members

therefore it is required to be a collection of resources.

partitionAccess is different. it is an attribute of a user resource and not a distinct url

**Comment by gabrielfortin** [comment]
Oh I see! Thank you

**Comment by caphrim007** [comment]
@GabrielFortin closing this as I suspect that you're good to go.
