### ISSUE TITLE
How to use this codes?

### ISSUE THREAD

**Issue by Ironman-india** [F5Networks/f5-common-python#1165]
I am F5 engineer , not a programmer.
Need to build SDK for automation using python?

How i use this codes in my laptop,  I installed python 3
i am seeing more files and codes, need help on this\

please let me know step by step, so i grap to develop project

**Comment by caphrim007** [comment]
@Ironman-india have you looked at the documentation yet? It includes a basic example

http://f5-sdk.readthedocs.io/en/latest/

**Comment by Ironman-india** [comment]
Thanks, I am reading it. let me ask your help if i need. 
can you suggest some books for python SDK build?
I am network engineer , assigned the project for build the python SDK to configure the remote devices
like F5 and palo firewall for configure changes!!!

**Comment by caphrim007** [comment]
@Ironman-india there are no books written for the python sdk. If you're not familiar with python though, you might want to start here https://www.learnpython.org/

Otherwise, the python-sdk documentation I mentioned earlier will bring you up to speed on using it. There should also be some articles on https://devcentral.f5.com/. search for "f5-sdk" there.

**Comment by vsnine** [comment]
Hi Ironman, 
You may want to consider looking into whether Ansible fits your needs. F5 has published Ansible modules to do what you need, since they don't require much knowledge of Python. Ansible has modules for Palo Alto, as well.

**Comment by wojtek0806** [comment]
closing as answered

**Comment by Ironman-india** [comment]
Thanks for all
