### ISSUE TITLE
How to get/set external datagroup content?

### ISSUE THREAD

**Issue by lrhazi** [F5Networks/f5-common-python#1272]
Looking at the test _test_data_group.py_ , I do not see an attempt to test uploading new content for an external datagroup, nor even getting the current content.

Is that not possible?

**Comment by caphrim007** [comment]
@lrhazi the answer to your question is "yes" and "ermm...maybe".

First, the test for uploading new content, "yes" it appears that we do not have a test for it. Continue reading.

Second, "is that possible?". The easiest answer is "no" without getting into too deep a technical discussion. However, there is a semi-acceptable workaround

TMUI (the web interface) does indeed provide you with the ability to manage the content of an external data-group. The problem from f5-sdk point-of-view is that that data is in the "Managed Storage" of BIG-IP and it is questionable whether or not there is an API to access that.

You might ask why the two are not equal, and the answer is because TMUI has A LOT of fingers that creep into the innards of the BIG-IP system and bypass the more proper channels. Sad trombone

Below is a fragement of code that illustrates how you might "know" if the data-group on your BIG-IP is different than the data-group you have on your local machine.

```
from f5.bigip import ManagementRoot
import hashlib

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

mgmt = ManagementRoot('localhost', 'admin', 'admin', port=10443)

content1 = """
"foo" := "1234",
"bar" := "5678",
"baz" := "abcd",
"""

with open('file1.txt', 'w') as fh:
    fh.write(content1)

# upload data-group files
mgmt.shared.file_transfer.uploads.upload_file('file1.txt')

# Add the files in BIG-IP file management
f1d = mgmt.tm.sys.file.data_groups.data_group.create(
    name='file1',
    type='string',
    sourcePath='file:///var/config/rest/downloads/file1.txt'
)

# Create external data-group
new = mgmt.tm.ltm.data_group.externals.external.create(
    name='foo2',
    externalFileName=f1d.fullPath
)
m = hashlib.sha1()
m.update(content1)


print("This is the hash on local disk ", m.hexdigest())
print("This is the hash on BIG-IP ", f1d.checksum)


content2 = """
"bar" := "5678",
"baz" := "abcd",
"foo" := "1234",
"""

with open('file1.txt', 'w') as fh:
    fh.write(content2)

# upload changed external data-group file
mgmt.shared.file_transfer.uploads.upload_file('file1.txt')

# You need to update here because BIG-IP doesn't actually use this
# file for your data group. BIG-IP instead copies the file you specify
# into a place called "Managed Storage".
#
# You can see the REAL data content by navigating to 
#
#    /config/filestore/files_d/Common_d/datagroup_d/:Common:file_1
#
# on the BIG-IP
f1d.update(
    type='string',
    sourcePath='file:///var/config/rest/downloads/file1.txt'
)
f1d.refresh()

m = hashlib.sha1()
m.update(content2)

print("This is the updated hash on local disk ", m.hexdigest())
print("This is the updated hash on BIG-IP ", f1d.checksum)
```

If you run that, you should expect to get an output that resembles the following

```
(ansible-dev) SEA-ML-RUPP1:f5-common-python trupp$ python try.py 
('This is the hash on local disk ', '991d6410179ee69f187a37f28929e4851aa22d42')
('This is the hash on BIG-IP ', u'SHA1:52:991d6410179ee69f187a37f28929e4851aa22d42')
('This is the updated hash on local disk ', '49757dafd95745a1a6fac44be5caa565b752e2fb')
('This is the updated hash on BIG-IP ', u'SHA1:52:49757dafd95745a1a6fac44be5caa565b752e2fb')
```

Thus illustrating how you can "know". The trick is that you must compare the checksum of the content on disk with the checksum of the content on BIG-IP. This is the easier way to know if your data-group has changed.

However, the argument could be made that by just shuffling the data you can have a different checksum while still arguably having the same data.

If you're really truly looking to compare content to content, then you need to utilize the "bash over REST" abilities of the REST API,

- literally, copy the file out of the Managed Storage to a place you can download it from
- download it from its new location
- open it and read all the content you downloaded
- compare what you have read with what you have on hand

Yes, you cannot "just open it" as-in a remote file because BIG-IP sends you data in chunks that you need to assemble. It's not a normal web-server in that you can just "GET" and walk away with data. So you must do step 2 and 3.

It should be clear by now that your first option of comparing checksums is the lesser of two evils. Note however that comparison of BIG-IP's checksum requires that you remove some extra prefix information.

A BIG-IP checksum looks like this

`SHA1:52:49757dafd95745a1a6fac44be5caa565b752e2fb`

So you must remove the `SHA1:52:` part of the string. That part is essentially telling you

- SHA1 = the hash that you're about to see
- 52 = size, in bytes, of the original file
- ... = the actual hash of those bytes

Hope this helps.

**Comment by lrhazi** [comment]
Thank you so much for the comprehensive response. This should be in FAQ or HOWTO I guess. Thanks a lot.

**Comment by caphrim007** [comment]
@jasonrahm in case you want to re-publish this in any part, or its entirety, on DevCentral, per @lrhazi's comment
