### ISSUE TITLE
How to enable verification for HTTPs?

### ISSUE THREAD

**Issue by zlesnr** [F5Networks/f5-common-python#1277]
I see that some of the icontrol classes allow for verification of HTTPs sessions, but there doesn't seem to be a way to pass that through the bigip ManagementRoot class.

**Comment by caphrim007** [comment]
@zlesnr at this time there is not a way, though the underlying code in the session library we use has recently started to support this. We should add a `validate_certs` as well as a method for accepting a cert to check with. This should be along the lines of
- look in /etc/ssl/certs, /usr/local/etc/openssl for a valid cert
- if the parameter `client_cert` is provided, use that file to do validation instead of looking in the above locations.

**Comment by jasonrahm** [comment]
@caphrim007 is this a different issue than was addressed in #1338 ?

**Comment by caphrim007** [comment]
I think they are the same and that this was addressed in 1338

**Comment by jasonrahm** [comment]
Hi @zlesnr, this was added in development branch based on 3.6, and was released in 3.7. When instantiating with ManagementRoot, add the kwarg verify=True and you should be good to go.
