### ISSUE TITLE
client ssl modification issue

### ISSUE THREAD

**Issue by alexnimo** [F5Networks/f5-common-python#1452]
Hi,

Not sure if it's a bug or I'm doing something wrong.
When trying to modify client ssl profile with a specific option, it turns on all of the options in the profile.
simple example:
`en_mode = {'mode':'enabled'}`
`sslprof.modify(**en_mode)`
`sslprof.update()`

This will turn on all of the profile options...
screenshot attached:
![image](https://user-images.githubusercontent.com/25372741/40716924-3afdd2e8-6413-11e8-90fd-486c6f7b4840.png)

**Comment by penghon** [comment]
Print screen shows only one option enabled. The rest are in the available
options field, not yet enabled.

**Comment by wojtek0806** [comment]
en_mode = {'mode':'enabled'}
sslprof.modify(**en_mode) <== this command is enough to make changes
sslprof.update() <=== this is the issue

update() method uses PUT whereas modify() uses PATCH, when using PUT method we allow F5 to set other settings to default, which is why you see this. 

Besides this, you should not use update() after modify as this is redundant. Using modify() is enough and is recommended.

**Comment by alexnimo** [comment]
Thanks for the explanation!
`update()` was the issue!

**Comment by wojtek0806** [comment]
i am glad this helped, ill close the issue now, if you have any other problems let us know
