### ISSUE TITLE
How to get dynamic arps entries?

### ISSUE THREAD

**Issue by salvapinyol** [F5Networks/f5-common-python#1583]
Hi:

Doing a get request to _/mgmt/tm/net/arp/stats_ I'm able to get the dynamic arp list on the device.

But I don't know how this can be done with f5-sdk, because it seems that call to:

_mgmt.tm.net.arps.get_collection()_ 

is only for static arp entries.

How can access to _/mgmt/tm/net/arp/stats_ using f5-sdk?

**Comment by f5-rahm** [comment]
stats is built such that you need to load the object and then get the stats from that object like this:

arp = b.tm.net.arps.arp.load(name='10.10.10.10')
arpstats = arp.stats.load()

however, because the arp stats are returned on dynamic objects, this doesn't exactly work, does it? Might need to get these from the bash utility if using this library. I'd be happy to be proven wrong.

All that said, this library is no longer under development. I'd recommend [bigrest](https://bigrest.readthedocs.io/), it's currently under active development and handles this just fine:

```
from bigrest.bigip import BIGIP
br = BIGIP('10.0.2.15', 'admin', 'admin')
arps = br.show('/mgmt/tm/net/arp')
for arp in arps:
    print(arp.properties.get('ipAddress').get('description'))
10.0.4.20
10.0.4.21
10.0.4.22
```

**Comment by salvapinyol** [comment]
@f5-rahm Thanks a lot for your advice.

I'll check the bigrest library.
