### ISSUE TITLE
Support for determining the state of a bigip device

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#302]
A user of this sdk should be able to determine if the BigIP is licensed and active or not. We aren't quite sure what type of query is needed to determine the state, but @szakeri may have more information.

**Comment by wojtek0806** [comment]
The state of the device can be discovered by querying the following REST endpoint:
"/mgmt/tm/shared/bigip-failover-state"
As far as licensing goes, the information on licensed modules and licensed state can be found under:
"/mgmt/tm/shared/licensing/registration"
There is also another endpoint that deals with license activation state (that would be probably useful to check the progress of license install.
This is the endpoint: "/mgmt/tm/shared/licensing/activation"
GET request works for those endpoints. I am not sure how would this translate to the methods in the SDK, load() maybe? since this seems like a resource

**Comment by swormke** [comment]
This is probably an `UnamedResource` similar to `f5.bigip.sys.global_settings`, that requires a new `OrganizingCollection` module called `shared` based on the URI.
