### ISSUE TITLE
FDB needs to support a 11.5.0 api version only

### ISSUE THREAD

**Issue by rc979** [F5Networks/f5-common-python#314]
Are you planning on adding FDB support here soon? It seems most of the work is done.

**Comment by swormke** [comment]
@rc979 yes, it should be there in the next release scheduled for 4/1/2106.

**Comment by swormke** [comment]
@rc979 issue #239 addressees this. Is there functionally missing that you expected to see?

**Comment by rc979** [comment]
Thanks for getting back to me. No, no additional functionality, just
wondering what other modules are not enabled yet?

**Comment by swormke** [comment]
@rc979 we have taken the approach of prioritizing our current largest user F5Networks/f5-openstack-agent for the supported objects.  That said adding objects is usually pretty straight foward and I am generating a Devguide right now (issue #318 ).

I know the code probably looks incomplete, but this is what most modules look like due to the architecture of the SDK.  The easiest way to see what objects are supported is to look at the doc's starting with the [organizing collection](https://f5-sdk.readthedocs.org/en/latest/apidoc/f5.bigip.html#organizing-collection-modules) to see what modules are supported under each one of them.

**Comment by swormke** [comment]
After talking with @rc979 offline I understand what is going on here.  Looks like we need to add this as a lazy attribute to net.  Also looks like we must force the 11.6.0 version of the API for this.  I will take care of these issues in this one.
