### ISSUE TITLE
Add UCS Support

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-common-python#453]
Add support to F5 Python SDK for managing UCS archives (create/save, restore, list).
/mgmt/tm/sys/ucs

**Comment by wojtek0806** [comment]
Due to ID504814 we cannot list the UCS archives that are on the system. Load and Save should be achievable using command mixin.

**Comment by wojtek0806** [comment]
It seems this feature is riddled with bugs, as per research and testing:

**11.6.0** 
- Listing UCS does not work due to ID504814

Simple GET to '/mgmt/tm/sys/ucs/' returns just the below:

```
{"kind":"tm:sys:ucs:ucscollectionstate","selfLink":"https://localhost/mgmt/tm/sys/ucs?ver=11.6.0"}

```
- Loading UCS returns { "command":"load", "name": "test.ucs"} :

```
{"code":500,"message":"UCS loading process failed.","errorStack":[]}

```

And we have no way of telling if this succeeded or not
- Saving UCS returns { "command":"save", "name": "test2.ucs"}:

```
{"code":500,"message":"UCS saving process failed.","errorStack":[]}
```

but it succeeds as the ucs file is created, verified on the device.

There are some other syntax examples where one uses payload like this:

{ "command":"save", "options":[{"ucs":"test6.ucs"}]}

but on 11.6.0 and 12.x it returns the error:

```
{"code":400,"message":"\"test6.ucs\" unknown property","errorStack":[]}

```

**12.x.0** 
- Listing UCS does works in 12.1.0 and  simple GET to '/mgmt/tm/sys/ucs/' returns something like this:

```
{
  "kind": "tm:sys:ucs:ucscollectionstate",
  "selfLink": "https://localhost/mgmt/tm/sys/ucs?ver=12.1.0",
  "items": [
    {
      "kind": "tm:sys:ucs:ucsstate",
      "generation": 0,
      "apiRawValues": {
        "base_build": "0.0.606",
        "build": "0.3.606",
        "built": "150930180821",
        "changelist": "1513591",
        "edition": "Engineering Hotfix",
        "encrypted": "no",
        "file_size": "104923292 (in bytes)",
        "filename": "/var/local/ucs/config.ucs",
        "install_date": "Wed Sep 30 18:08:21 PDT 2015",
        "job_id": "553417",
        "product": "BIG-IP",
        "sequence": "12.0.0.0.3.606.3",
        "version": "12.0.0"
      }
    },
```
- Loading UCS returns { "command":"load", "name": "test.ucs"} : 

```


<body>
<h1>Bad Gateway!</h1>
<p>


    The proxy server received an invalid
    response from an upstream server.


    </p>
<p>

    The proxy server could not handle the request <em><a href="/mgmt/tm/sys/ucs/">POST&nbsp;/mgmt/tm/sys/ucs/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p>


</p>

<h2>Error 502</h2>
<address>
  <a href="/">ltm6</a><br />

  <span>Thu Jun 23 00:30:39 2016<br />
  </span>
</address>
</body>
</html>
```

Again we have no way of telling if it suceeded or not
- Saving UCS returns { "command":"save", "name":"test4.ucs"}:

```
{"kind":"tm:sys:ucs:savestate","command":"save","name":"test4.ucs"}
```

Which is what we want

I am going to try few other things but it does not look good now

**Comment by wojtek0806** [comment]
Good News! the below works on both 11.6.0 and 12.x.0, but it still returns Bad Gateway 502

This is definitely a bug with REST not returning proper response. 
To verify this was successful I did tail -f /var/log/ltm and I have seen config loading.

```
{"command":"load", "utilCmdArgs": "test4.ucs no-license"}
```

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Bad Gateway!</title>
<link rev="made" href="mailto:support@f5.com" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
* { width: 400px; font-size: 100%; font-style: normal; }
html { text-align: center; }
body { background: #ffffff; text-align: left; font-family: sans-serif; font-size: 70%; color: #333333; }

a,span { width: auto; } 
h1,h2,h3 { margin: 20px 0px 20px 0px; font-weight: bold; }

h1 { padding: 5px; border: 1px solid #999999; background: #eeeeee; color: #000000; font-size: 125%;  }
hr { height: 1px; border: none; border-top: 1px solid #999999; }
img { border: 0px; }
p { width: 350px; margin: 15px 25px 15px 25px; line-height: 135%; }
/*]]>*/--></style>

</head>

<body>
<h1>Bad Gateway!</h1>
<p>


    The proxy server received an invalid
    response from an upstream server.


    </p>
<p>

    The proxy server could not handle the request <em><a href="/mgmt/tm/sys/ucs/">POST&nbsp;/mgmt/tm/sys/ucs/</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p>


</p>

<h2>Error 502</h2>
<address>
  <a href="/">ltm5</a><br />

  <span>Thu Jun 23 00:44:22 2016<br />
  </span>
</address>
</body>
</html>
```
- Running the command:

```
{"command":"save", "utilCmdArgs": "test4.ucs"}
```

still returns on 11.6.0 Final

```
{"code":500,"message":"UCS saving process failed.","errorStack":[]}
```

**SIDENOTE:**
Seems like utilizing OPTIONS is not the best approach, could be due to the fact that the examples I have found did not have correct syntax, i found it easier to use 'utilCmdArgs' as it felt more natural in mimicking tmsh syntax

**Comment by wojtek0806** [comment]
@zancas @pjbreaux @caphrim007 

I need some insight on how we wanna approach this, given the amount of issues implementing of this 'feature' would present. 

I am going to open an internal escalation to clarify why we do not get valid response when attempting to load the UCS on 12.1.0.

**Comment by wojtek0806** [comment]
Update to my SIDENOTE, it seems the syntax observed is correct, so it does look like node.js issue. I am querying this in my escalation as well.

**Comment by wojtek0806** [comment]
Looks like 502 response is expected due to daemons restarting upon UCS load. Will raise RFE to improve this behavior but for now, I have to get creative and hack this a bit so it is workable. It won't be pretty

**Comment by wojtek0806** [comment]
I was a bit hasty with 11.6.0 Final, it seems load UCS does not work on this version. Due to the amount of issues, I am arbitarily,  making this feature v12.x and up only for now
