### ISSUE TITLE
Add list of supported TMOS versions in the Returned Exception

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-common-python#491]
After upgrading to 0.1.7 existing code from 0.1.5 breaks.  

Python 2.7.6 (Ubuntu 14.04)
TMOS 12.1.0

Example:

```
0.1.5:
%cat foo.py
from f5.bigip import BigIP

# Connect to the BigIP
bigip = BigIP("10.1.1.2", "admin", "admin")

# Get a list of all pools on the BigIP and print their name and their
# members' name
pools = bigip.ltm.pools.get_collection()
for pool in pools:
    print pool.name
    for member in pool.members_s.get_collection():
         print member.name
%python foo.py
...
172.16.63.2:80
172.16.77.2:80
172.16.86.3:80
% pip install --upgrade  f5-sdk
% python foo.py
...
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    pools = bigip.ltm.pools.get_collection()
  File "/XXX/ENV/local/lib/python2.7/site-packages/f5/bigip/mixins.py", line 113, in __getattr__
    container._check_supported_versions(attribute)
  File "/XXX/ENV/local/lib/python2.7/site-packages/f5/bigip/mixins.py", line 124, in _check_supported_versions
    raise UnsupportedTmosVersion(error)
f5.bigip.mixins.UnsupportedTmosVersion: There was an attempt to access API which has not been implemented or supported in the device's TMOS version: 12.1.0
```

**Comment by wojtek0806** [comment]
@chen23 
Thank you for reporting this, the SDK currently supports versions 11.6.0 and 12.0.0 only.

**Comment by chen23** [comment]
It would be helpful if the exception printed a list of supported versions and/or link to a list.  Similar ask for documenting supported version(s) of Python/TMOS with the SDK Docs.  Thank you.

**Comment by wojtek0806** [comment]
I think this is a good idea, I will take this issue and rename it  so i can implement this

**Comment by wojtek0806** [comment]
@zancas, @pjbreaux , @caphrim007  

I have been thinking of doing something like this:

https://gist.github.com/wojtek0806/a766d2bf2d951f5510bd2766cf7f7fea

This way we can prevent the SDK running on non supported versions.

**Comment by caphrim007** [comment]
@wojtek0806 @zancas I said this before in the Slack channel but i think it's a bad idea to specifically list the versions of TMOS that the SDK supports...specifically for the reason that this issue points out.

I had said before that we should instead be comparing greater-than and less-than using StrictVersion because of situations _exactly_ like this one; people using the SDK on versions we haven't yet tried it on.

It's more appropriate to do that and list it in the documentation that this is what we support than it is to hard-code it like this in the SDK.

Another point is that when the SDK is inevitably abandoned, all future versions of BIG-IP will be unable to use it. At that point the customers will, yet again, need to maintain things or abandon them and start over...again.

It's more practical to specify a minimum_version in the base and then override that in all classes where that minimum is no longer valid. Then use StrictVersion to check that.

My 2c

**Comment by wojtek0806** [comment]
Why? we should be preventing usage of the SDK against the untested TMOS versions. Once we have passing tests then we can allow it, it is very simple you cannot make something to be compatible for everything, without testing, as it opens another can of worms like raising issues against untested versions.

**Comment by chen23** [comment]
I would personally favor an option to override the list of supported versions, something like:

```
from f5.bigip import ManagementRoot

# Connect to the BigIP
mgmt = ManagementRoot("bigip.example.com", "admin", "somepassword",unsupported_version='12.1')
```

It creates its own set of issues (what happens when 12.1 is supported.  this can't bypass the case where something is being explicitly discarded (i.e. 11.6.0)).

Regardless of the decision it would be helpful that it is obvious to the programmer in code/documentation.  Thanks!

**Comment by zancas** [comment]
We don't want it to be impossible to use the SDK if your device is too new!   I think @tar 's suggestion sounds sane.    I'll look into this in more detail tomorrow.

**Comment by zancas** [comment]
@chen23 we'll fix this bug so that the SDK works for newer versions of the device.

**Comment by zancas** [comment]
@chen23 we intend to release a bugfix this Friday that will make the SDK "just work" again for 12.1.

**Comment by caphrim007** [comment]
@wojtek0806 @zancas I am of the opinion that we should be future-proofing ourselves and our customers against lack of development; as F5 is notorious for this. If we lock in to specific versions then we cannot even test new versions until we adapt the code.

imho this is no different from every other open source project on earth. The core developers have a specific agenda and they work on that, but that does not preclude someone from using the software beyond what it is documented to support.

If they choose to do that, then they are on their own. Just to reinforce that point, call it out specifically on the front-page of the readme that, as far as we know, this only works on these enumerated platforms that we have tested.

**Comment by zancas** [comment]
@caphrim007 +1

**Comment by wojtek0806** [comment]
added to 0.1.8 closing

**Comment by rdelpret** [comment]
Hello, I have 2 Big IPs both running the same TMOS version, iControl version and running the exact same configuration. On the first accessing the pool list works fine with bigip.ltm.nodes.get_collection() and on the other it returns (running python 2.6 for both):

Traceback (most recent call last):
  File "./check_pools", line 165, in <module>
    check_pools(sites['*****_'], '**_**_', '**_*****')
  File "./check_pools", line 82, in check_pools
    nodes = node_list(bigip.ltm.nodes.get_collection())
  File "/usr/lib/python2.6/site-packages/f5/bigip/mixins.py", line 113, in **getattr**
    container._check_supported_versions(attribute)
  File "/usr/lib/python2.6/site-packages/f5/bigip/mixins.py", line 124, in _check_supported_versions
    raise UnsupportedTmosVersion(error)
f5.bigip.mixins.UnsupportedTmosVersion: There was an attempt to access API which has not been implemented or supported in the device's TMOS version: 11.5.4

on big ip 1: (working)

iControl-wsdl-11.5.4-0.0.256
iControl-handlers-11.5.4-0.0.256
iControl-11.5.4-0.0.256
iControl_java_client-11.5.4-0.0.256
iControl-modules-11.5.4-0.0.256

on big ip 2: (same code not working)

iControl-wsdl-11.5.4-0.0.256
iControl-handlers-11.5.4-0.0.256
iControl-11.5.4-0.0.256
iControl_java_client-11.5.4-0.0.256
iControl-modules-11.5.4-0.0.256

**Comment by rdelpret** [comment]
nvm i downgraded the module and everything worked........

**Comment by zancas** [comment]
@wojtek0806 let's set the minimum version to 11.5.4

**Comment by wojtek0806** [comment]
@za i am against doing that, you are opening a door for trouble, this is untested and will only generate errors to users that they will query with us, since the error message clearly states minimum SUPPORTED version, this means this is SUPPORTED as in TESTED

**Comment by zancas** [comment]
@caphrim007 @swormke @wojtek0806 
I see your point @wojtek0806 I'm not suggesting that we should do extra work to support 11.5.4, but what if someone has an 11.5.4 device and their use-case is such that the SDK will work for them?  Is that unlikely?  Impossible?   If it's likely, then it seems like disallowing them from using the SDK as the solution helps no-one.   Since I'm not familiar with the details of 11.5.4 I'll defer to more expert opinions.

**Comment by rdelpret** [comment]
@wojtek0806 @zancas Perhaps make it a warning saying it is untested and your preceding at your own risk? This error broke a script that has been working perfectly fine for me. I ended up losing half a day troubleshooting and upgraded our second big ip's tmos version to match the first big ip in the process. After it still didn't work when both big ips were exactly the same the next variable was the server i was running the script from so I ran pip list to check the module versions and downgrading fixed my problem.

FWIW i also had to edit mixins.py 's string formatting to even throw this error message to find out what was wrong in the first place because it was using string formatting only supported in python 3. We have python 2.6 on our centos servers that can reach our big ips because upgrading it would break yum (package manager) so i always try to write any python code to be 2.6 compatible to avoid having to alt-install python.

So my 2 cents is that its not an error if its its keeping something from working.

**Comment by rdelpret** [comment]
My script can add servers to the big ip, create pools, add servers to pools, set ratios, health checks... I've had no issues using the sdk with 11.5.4 up until this.

**Comment by zancas** [comment]
I can think of no good reason to prevent @rdelpret from using the SDK...    it seems like shooting ourselves in the foot...  for no reason.

**Comment by zancas** [comment]
@rdelpret can you please open a PR with your fix to the print formatting in `mixins.py`.  I'd like to get that in ASAP.

**Comment by zancas** [comment]
@rdelpret are you in the f5-common-python slack team?

**Comment by rdelpret** [comment]
No I am not, how do I join?

**Comment by zancas** [comment]
Here's the URL:  https://f5openstackdev.slack.com/messages/f5-common-python/

Send me your email address at:  za@f5.com
