### ISSUE TITLE
Add a a Single Source of Truth for Python package dependencies. I vote for setup.py.

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#596]
This may/will require changing the logic in setup.py to set its values based on the contents of requirements.txt.   I'd be interested in thinking about going the other way also...   why not make 'setup.py' the single source of truth, and omit `requirements.txt` altogether?

**Comment by zancas** [comment]
I vote we make `setup.py` the single source of truth.  Then we can reserve "`requirements`" files for special purposes... like "`test`" and "`docs`".

**Comment by wojtek0806** [comment]
no objections there, and logical from user perspective

**Comment by ssorenso** [comment]
I've actually implemented a `setup_requirements.txt`... the `setup.py` is not easily portable due to the nature of how `setup.py` works with the setup utility.  Thus, I would have to parse the `setup.py` script, which is doable; however, very heavy and potentially a vulnerability bug-wise with the necessary moving parts.

This is also part of the requirement that the native-building docker files that both build and test for this should be as independent as possible from any tool that i might use to automate the parsing of the `setup.py` script.  There, we're trying to make it as barebones as possible, yet I would like the test automation to handle testing the passing of dependency names from the source versus what the packages are built for, and that's easier handled natively within the test docker container.

This is addressed in Issue #980

**Comment by wojtek0806** [comment]
closing as merged
