### ISSUE TITLE
ltm policy functional rewrite in tmos version 12.1 needs attention in sdk

### ISSUE THREAD

**Issue by jasonrahm** [F5Networks/f5-common-python#668]
In 12.1, policies cannot just be created and attached to virtual servers. There is a workflow to create a draft, then publish, then attach. For existing policies, you need to create a draft of the policy, patch the draft, then publish it. Steps to update a published draft using obscure combo using options and payloads with “command” :-) (provided by Alex A)

```
(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X PATCH -d '{"partition":"Common"}' -sk https://x.x.x.x/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?options=create-draft | python -m json.tool
{
    "controls": [
        "asm"
    ],
    "draftCopy": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "draftCopyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0"
    },
    "fullPath": "/Common/ltm_policy_w_asm_linux_high-Vip1",
    "generation": 2697,
    "kind": "tm:ltm:policy:policystate",
    "lastModified": "2016-08-23T21:34:58Z",
    "name": "ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common",
    "references": {},
    "requires": [
        "http"
    ],
    "rulesReference": {
        "isSubcollection": true,
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1/rules?ver=12.1.0"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?options=create-draft&ver=12.1.0",
    "status": "published",
    "strategy": "/Common/first-match",
    "strategyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy-strategy/~Common~first-match?ver=12.1.0"
    }
}

Then you patch the draft copy
(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X PATCH -d '{"name":"ltm_policy_w_asm_linux_high-Vip1","partition":"Common","subPath":"Drafts","controls":["asm"],"requires":["http"],"strategy":"/Common/first-match","rules":[{"name":"rule-1","ordinal":1,"actions":[{"name":"0","asm":true,"code":0,"enable":true,"policy":"/Common/linux_high-Vip1","port":0,"request":true,"status":0,"vlanId":0}],"conditions":[]}]}' -sk https://x.x.x.x/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0 | python -m json.tool
{
    "controls": [
        "asm"
    ],
    "fullPath": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "generation": 2745,
    "kind": "tm:ltm:policy:policystate",
    "lastModified": "2016-08-24T17:42:34Z",
    "name": "ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common",
    "publishedCopy": "/Common/ltm_policy_w_asm_linux_high-Vip1",
    "publishedCopyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0"
    },
    "references": {},
    "requires": [
        "http"
    ],
    "rulesReference": {
        "isSubcollection": true,
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1/rules?ver=12.1.0"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0",
    "status": "draft",
    "strategy": "/Common/first-match",
    "strategyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy-strategy/~Common~first-match?ver=12.1.0"
    },
    "subPath": "Drafts"
}

Then publish the draft.
(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X POST -d '{"name":"/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1","command":"publish"}' -sk https://x.x.x.x/mgmt/tm/ltm/policy | python -m json.tool
{
    "command": "publish",
    "kind": "tm:ltm:policy:publishstate",
    "name": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common"
}
```

**Comment by jasonrahm** [comment]
new functionality in sdk will be necessary for #575 to be evaluated and functional tests updated

**Comment by alexapplebaum** [comment]
Full Workflow managing LTM policies in 12.x:

1st Upload:

Need to first create it in draft folder. 

Otherwise, get this now:

{
    "apiError": 3,
    "code": 400,
    "errorStack": [],
    "message": "01071abb:3: Cannot create/modify published policy '/Common/ltm_policy_w_asm_linux_high-Vip1' directly, try specifying a draft folder like '/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1'."
}

1st POST needs "subPath":"Drafts" in the payload:

(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X POST -d '{"name":"ltm_policy_w_asm_linux_high-Vip1","partition":"Common","subPath":"Drafts","controls":["asm"],"requires":["http"],"strategy":"/Common/first-match","rules":[{"name":"rule-1","ordinal":1,"actions":[{"name":"0","asm":true,"code":0,"enable":true,"policy":"/Common/linux_high-Vip1","port":0,"request":true,"status":0,"vlanId":0}],"conditions":[]}]}' -sk https://x.x.x.x/mgmt/tm/ltm/policy | python -m json.tool
{
    "controls": [
        "asm"
    ],
    "fullPath": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "generation": 1041,
    "kind": "tm:ltm:policy:policystate",
    "lastModified": "2016-08-23T17:10:44Z",
    "name": "ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common",
    "references": {},
    "requires": [
        "http"
    ],
    "rulesReference": {
        "isSubcollection": true,
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1/rules?ver=12.1.0"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0",
    "status": "draft",
    "strategy": "/Common/first-match",
    "strategyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy-strategy/~Common~first-match?ver=12.1.0"
    },
    "subPath": "Drafts"
}

Publish Draft (payload with the full path "name" of the draft and “command":"publish"):

(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$  curl -u admin:'admin' -H "Content-Type: application/json" -X POST -d '{"name":"/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1","command":"publish"}' -sk https://x.x.x.x/mgmt/tm/ltm/policy | python -m json.tool
{
    "command": "publish",
    "kind": "tm:ltm:policy:publishstate",
    "name": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common"
}

To Modify Existing Published Policy, you now PATCH with the query string "options=create-draft"

(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X PATCH -d '{"partition":"Common"}' -sk https://x.x.x.x/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?options=create-draft | python -m json.tool
{
    "controls": [
        "asm"
    ],
    "draftCopy": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "draftCopyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0"
    },
    "fullPath": "/Common/ltm_policy_w_asm_linux_high-Vip1",
    "generation": 2697,
    "kind": "tm:ltm:policy:policystate",
    "lastModified": "2016-08-23T21:34:58Z",
    "name": "ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common",
    "references": {},
    "requires": [
        "http"
    ],
    "rulesReference": {
        "isSubcollection": true,
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1/rules?ver=12.1.0"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?options=create-draft&ver=12.1.0",
    "status": "published",
    "strategy": "/Common/first-match",
    "strategyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy-strategy/~Common~first-match?ver=12.1.0"
    }
}

Then patch the draft copy just created:

(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X PATCH -d '{"name":"ltm_policy_w_asm_linux_high-Vip1","partition":"Common","subPath":"Drafts","controls":["asm"],"requires":["http"],"strategy":"/Common/first-match","rules":[{"name":"rule-1","ordinal":1,"actions":[{"name":"0","asm":true,"code":0,"enable":true,"policy":"/Common/linux_high-Vip1","port":0,"request":true,"status":0,"vlanId":0}],"conditions":[]}]}' -sk https://x.x.x.x/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0 | python -m json.tool
{
    "controls": [
        "asm"
    ],
    "fullPath": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "generation": 2745,
    "kind": "tm:ltm:policy:policystate",
    "lastModified": "2016-08-24T17:42:34Z",
    "name": "ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common",
    "publishedCopy": "/Common/ltm_policy_w_asm_linux_high-Vip1",
    "publishedCopyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0"
    },
    "references": {},
    "requires": [
        "http"
    ],
    "rulesReference": {
        "isSubcollection": true,
        "link": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1/rules?ver=12.1.0"
    },
    "selfLink": "https://localhost/mgmt/tm/ltm/policy/~Common~Drafts~ltm_policy_w_asm_linux_high-Vip1?ver=12.1.0",
    "status": "draft",
    "strategy": "/Common/first-match",
    "strategyReference": {
        "link": "https://localhost/mgmt/tm/ltm/policy-strategy/~Common~first-match?ver=12.1.0"
    },
    "subPath": "Drafts"
}

Then to publish the draft, use "command":"publish" again:

(venv)ubuntu@ip-172-16-13-92:~/aws-deployments$ curl -u admin:'admin' -H "Content-Type: application/json" -X POST -d '{"name":"/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1","command":"publish"}' -sk https://x.x.x.x/mgmt/tm/ltm/policy | python -m json.tool
{
    "command": "publish",
    "kind": "tm:ltm:policy:publishstate",
    "name": "/Common/Drafts/ltm_policy_w_asm_linux_high-Vip1",
    "partition": "Common"
}

**Comment by chen23** [comment]
worth mentioning that in 12.1 the API also adds a "legacy" field to skip the workflow.  Not recommending that, but should be considered whether this is exposed via the SDK.

**Comment by pjbreaux** [comment]
Thanks @chen23, I will let the user decide to user the legacy field or not.
