### ISSUE TITLE
RPM package does not specify the correct requirements

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-common-python#849]
The sdk package specifies dependencies on six and ordereddict in the requirements, but these dependencies are not found in setup.cfg.

**Comment by wojtek0806** [comment]
@richbrowne 
i believe this was fixed with PR #950 ?

**Comment by ssorenso** [comment]
This was fixed in Issue #950 as a quick fix.  The larger fix to handle a 'one source of truth' aspect is being addressed in #980.  Future growth could put the 'one source of truth' else where in the code, and that portion could be handled with 1 function change in each of the `fetch_and_install_deps.py` scripts in testing (there's one for Redhat CentOS 7 and one for Debian Ubuntu 'Trusty' 14.04) and in the `construct_setups.py`.  The `construct_setups.py` script is a standalone and can be developed on its own; however, we'll have to make sure that the change, logically, occurs roughly where I'm creating the `stdeb.cfg` and the `setup.cfg` files.  Otherwise, more work.

**Comment by wojtek0806** [comment]
closing as merged
